[package]
name = "staticAnalysis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4.28"
rand = "0.9.2"
regex = "1.12.2"
yara-x = { git = "https://github.com/VirusTotal/yara-x" }
